apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:lts-community
        ports:
        - containerPort: 9000
        env:
        - name: SONAR_ES_BOOTSTRAP_CHECKS_DISABLE
          value: "true"   # utile pour éviter des erreurs d'ES en mode simple
        volumeMounts:
        - mountPath: /opt/sonarqube/data
          name: sonar-data
        - mountPath: /opt/sonarqube/extensions
          name: sonar-extensions
      volumes:
      - name: sonar-data
        emptyDir: {}   # ⚠️ stockage temporaire (les données disparaissent si le pod redémarre)
      - name: sonar-extensions
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 32001

